# Autogenerated wrapper script for slope_jll for x86_64-linux-gnu
export libslopejll

using CompilerSupportLibraries_jll
using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("slope")
JLLWrappers.@declare_library_product(libslopejll, "libslopejll.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libslopejll,
        "lib/libslopejll.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
